baseURL = "http://rafaelleru.github.io/"
languageCode = "en-us"
title = "Rafael Leyva Ruiz"
theme = "ezhil"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  # Content types which are included in home page recent posts list.
  #mainSections = ["posts"]

  mode = "light" 

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/blog"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rafaelleru"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/rafa-leyva-738228140/"


[[params.social]]
name = "Stack Overflow"
icon = "StackOverflow"
url = "https://www.linkedin.com/in/rafa-leyva-738228140/"

# Enable tags.
[taxonomies]
   tag = "tags"
